Repository ACM-Thapar/ACM-Blockchain, pull requests merged in 2022-10, with the labels that each got.

#6 Added algo for block rewards and node integration
  cmd/acmt/run.go
  database/block.db
  database/block.go
  database/state.go
  fs/fs.go
Labels: hacktoberfest, hacktoberfest-accepted

#7 Test for mining and node integration
  node/miner_test.go
  node/node_integration_test.go
Labels: hacktoberfest, hacktoberfest-accepted

#9 Node connection bug fixed
  cmd/acmt/main.go
  database/state.go
  node/http_routes.go
  node/node.go
  node/sync.go
Labels: hacktoberfest-accepted

#11 Added Command and algo for wallets
  cmd/acmt/main.go
  cmd/acmt/wallet.go
  go.mod
  go.sum
  wallet/wallet.go
Labels: hacktoberfest-accepted

#12 added command to get private key from public key
  cmd/acmt/main.go
  cmd/acmt/wallet.go
  go.mod
Labels: enhancement, hacktoberfest-accepted

#14 Updated Readme.md
  README.md
Labels: hacktoberfest-accepted
